apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  resources: 
    requests:
      storage: 5Gi
  storageClassName: standard-fast
