apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db_volume
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  resources: 
    requests:
      storage: 4Gi
  storageClassName: standard
