apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchlabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: db_volume
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:V1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSOWRD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
    